server:
  port: 8880
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staff?useUnicode=true&characterEncoding=utf-8
    password: Mysql@123
    username: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: com.staff
  expiration: 1800000
request:
  login:
    url: /users/login
  swagger:
    url: /webjars
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
